export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  category: string;
  keywords: string;
  author: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "ai-agents-for-small-business-2026",
    title: "AI Agents for Small Businesses in 2026: A Practical Adoption Blueprint",
    description: "A practical guide to adopting AI agents for support, sales, and operations with measurable ROI and lower execution risk.",
    date: "2026-02-18",
    category: "AI",
    keywords: "ai agents 2026,small business ai automation,ai workflow setup,agentic ai guide",
    author: "Himal Pokhrel",
  },
  {
    slug: "ai-search-and-seo-in-2026",
    title: "AI Search and SEO in 2026: How Publishers Should Adapt",
    description: "A practical SEO playbook for AI assisted search experiences, entity visibility, and click worthy content in 2026.",
    date: "2026-02-18",
    category: "AI",
    keywords: "ai search seo 2026,seo for ai overviews,topical authority,structured content",
    author: "Himal Pokhrel",
  },
  {
    slug: "ai-video-generation-workflows-2026",
    title: "AI Video Generation Workflows in 2026: From Idea to Publish",
    description: "Build a repeatable AI video workflow for short form and long form content using scripts, visual prompts, and editing automation.",
    date: "2026-02-18",
    category: "AI",
    keywords: "ai video generation 2026,prompt to video workflow,ai content pipeline,short form video seo",
    author: "Himal Pokhrel",
  },
  {
    slug: "best-open-source-ai-models-2026",
    title: "Best Open Source AI Models in 2026: How to Choose the Right One",
    description: "Compare top open source model choices in 2026 and learn how to select by latency, quality, licensing, and deployment cost.",
    date: "2026-02-18",
    category: "AI",
    keywords: "open source ai models 2026,local llm guide,model benchmarking,ai model selection",
    author: "Himal Pokhrel",
  },
  {
    slug: "on-device-ai-explained-2026",
    title: "On Device AI Explained in 2026: Why Local Inference Is Growing",
    description: "Understand why on device AI is accelerating across phones, laptops, and edge hardware and what it means for builders.",
    date: "2026-02-18",
    category: "AI",
    keywords: "on device ai 2026,npu apps,edge ai strategy,hybrid ai architecture",
    author: "Himal Pokhrel",
  },
  {
    slug: "passkeys-adoption-guide-2026",
    title: "Passkeys Adoption Guide for 2026: Replacing Passwords the Right Way",
    description: "A rollout framework for passkeys across consumer products and enterprise environments in 2026.",
    date: "2026-02-18",
    category: "Tech",
    keywords: "passkeys 2026,passwordless login,identity security,passkey rollout",
    author: "Himal Pokhrel",
  },
  {
    slug: "zero-trust-security-for-modern-teams-2026",
    title: "Zero Trust Security for Modern Teams in 2026",
    description: "A practical zero trust plan for distributed teams using cloud apps, contractors, and multi device workflows.",
    date: "2026-02-18",
    category: "Tech",
    keywords: "zero trust security 2026,identity first security,remote team cybersecurity,least privilege",
    author: "Himal Pokhrel",
  },
  {
    slug: "edge-computing-for-ai-apps-2026",
    title: "Edge Computing for AI Apps in 2026: Where It Actually Wins",
    description: "Learn when edge computing beats cloud only architecture for AI applications and connected products.",
    date: "2026-02-18",
    category: "Tech",
    keywords: "edge computing ai 2026,edge inference,low latency architecture,hybrid cloud edge",
    author: "Himal Pokhrel",
  },
  {
    slug: "cloud-cost-optimization-for-ai-workloads-2026",
    title: "Cloud Cost Optimization for AI Workloads in 2026",
    description: "Control AI cloud spend using model routing, caching, observability, and smarter infrastructure choices.",
    date: "2026-02-18",
    category: "Tech",
    keywords: "ai cloud cost optimization,model routing strategy,token cost control,llm infrastructure",
    author: "Himal Pokhrel",
  },
  {
    slug: "practical-quantum-computing-progress-2026",
    title: "Practical Quantum Computing Progress in 2026: What Is Real",
    description: "Separate practical quantum milestones from hype and understand where near term business value may appear.",
    date: "2026-02-18",
    category: "Tech",
    keywords: "quantum computing 2026,quantum business strategy,quantum readiness,emerging tech trends",
    author: "Himal Pokhrel",
  },
  {
    slug: "bitcoin-etf-trends-2026",
    title: "Bitcoin ETF Trends in 2026: What Retail and Institutions Watch",
    description: "An educational breakdown of Bitcoin ETF market behavior, liquidity signals, and portfolio considerations in 2026.",
    date: "2026-02-18",
    category: "Crypto",
    keywords: "bitcoin etf 2026,crypto market trends,bitcoin investing education,etf liquidity",
    author: "Himal Pokhrel",
  },
  {
    slug: "stablecoins-for-global-payments-2026",
    title: "Stablecoins for Global Payments in 2026: Use Cases and Risks",
    description: "Understand how stablecoins are used for remittances, treasury operations, and online commerce with risk controls.",
    date: "2026-02-18",
    category: "Crypto",
    keywords: "stablecoin payments 2026,crypto remittance,digital dollar settlement,web3 payments",
    author: "Himal Pokhrel",
  },
  {
    slug: "ethereum-layer2-rollups-2026",
    title: "Ethereum Layer 2 Rollups in 2026: A Practical User Guide",
    description: "Learn how Ethereum Layer 2 networks work, where they help, and how users avoid common transfer and bridge mistakes.",
    date: "2026-02-18",
    category: "Crypto",
    keywords: "ethereum layer 2 2026,rollup guide,crypto bridge safety,low fee ethereum",
    author: "Himal Pokhrel",
  },
  {
    slug: "tokenized-real-world-assets-rwa-2026",
    title: "Tokenized Real World Assets in 2026: Opportunities and Limits",
    description: "An educational overview of tokenized real world assets and what teams should evaluate before participation.",
    date: "2026-02-18",
    category: "Crypto",
    keywords: "tokenized rwa 2026,real world asset crypto,tokenization trends,onchain finance",
    author: "Himal Pokhrel",
  },
  {
    slug: "crypto-risk-management-for-beginners-2026",
    title: "Crypto Risk Management for Beginners in 2026",
    description: "A beginner friendly framework for position sizing, custody safety, and volatility planning in crypto markets.",
    date: "2026-02-18",
    category: "Crypto",
    keywords: "crypto risk management,beginner crypto strategy,portfolio sizing crypto,crypto safety guide",
    author: "Himal Pokhrel",
  },
  {
    slug: "ai-pc-buying-guide-2026",
    title: "AI PC Buying Guide 2026: Specs That Actually Matter",
    description: "A buyer focused guide to AI PC hardware choices including NPU capability, battery life, memory, and real workflow impact.",
    date: "2026-02-18",
    category: "Consumer Electronics",
    keywords: "ai pc buying guide 2026,npu laptop specs,on device ai laptop,best ai computers",
    author: "Himal Pokhrel",
  },
  {
    slug: "smart-glasses-trends-2026",
    title: "Smart Glasses Trends in 2026: What Is Improving Fast",
    description: "An overview of smart glasses trends covering form factor, battery tradeoffs, privacy expectations, and practical use cases.",
    date: "2026-02-18",
    category: "Consumer Electronics",
    keywords: "smart glasses 2026,wearable display trends,ai eyewear guide,consumer tech trends",
    author: "Himal Pokhrel",
  },
  {
    slug: "wearable-health-tech-trends-2026",
    title: "Wearable Health Tech Trends in 2026: Signals Buyers Should Trust",
    description: "A practical guide to wearable health technology trends, metrics reliability, and buying decisions in 2026.",
    date: "2026-02-18",
    category: "Consumer Electronics",
    keywords: "wearable health tech 2026,fitness tracker trends,smartwatch health data,consumer health gadgets",
    author: "Himal Pokhrel",
  },
  {
    slug: "foldable-phone-buying-guide-2026",
    title: "Foldable Phone Buying Guide 2026: Who Should Upgrade",
    description: "Understand whether foldable phones are worth it in 2026 based on durability, software support, and real productivity needs.",
    date: "2026-02-18",
    category: "Consumer Electronics",
    keywords: "foldable phone 2026,best foldable buying guide,foldable durability,smartphone trends",
    author: "Himal Pokhrel",
  },
  {
    slug: "matter-smart-home-upgrade-guide-2026",
    title: "Matter Smart Home Upgrade Guide 2026: A Practical Path",
    description: "A step by step plan to upgrade a mixed smart home using Matter compatible devices and cleaner automation design.",
    date: "2026-02-18",
    category: "Consumer Electronics",
    keywords: "matter smart home 2026,smart home upgrade guide,thread network setup,connected home automation",
    author: "Himal Pokhrel",
  },
];

export const blogCategories = ["All", "AI", "Tech", "Crypto", "Consumer Electronics"] as const;
